apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: pv-data-storage
          persistentVolumeClaim:
            claimName: pvc-data
      containers:
      - name: app
        image: sonjagalovic/racunarstvo-u-oblaku:assignment-wine
        imagePullPolicy: Always
        command: ["python", "/app/app.py"]
        ports:
        - containerPort: 5000
        env:
        - name: data_path
          value: "/home/sonjag/assignment-wine/data/wine-quality-white-and-red.csv"
        - name: model_path
          value: "/home/sonjag/assignment-wine/data/wine-model.pkl"
        volumeMounts:
          - mountPath: "/home/sonjag/assignment-wine"
            name: pv-data-storage